name: Run Marker on changes

on:
  pull_request:
    paths:
      - "public/papers/**"
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  marker:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install marker and dependencies
        run: pip install marker-pdf openai markdown-it-py[plugins] tqdm
      - name: Cache Marker models
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/datalab/models/
          key: datalab-models-${{ runner.os }}
      - name: Run marker script for changed files
        shell: bash
        run: |
          changed_files=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" -- 'public/papers/*.pdf')
          echo "$changed_files" | while IFS= read -r file; do
            [ -z "$file" ] && continue
            ./scripts/run_marker.sh "$file"
          done
      - name: Commit marker outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Add marker outputs"
            git push origin HEAD:${{ github.head_ref }}
          fi
